# Generated by Django 3.0.5 on 2020-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('Magister', 'mgr'), ('Magister', 'mgr inż.'), ('Licencjat', 'lic.'), ('Inżynier', 'inż.'), ('Ksiądz', 'ks.'), ('Ksiądz', 'ks. mgr'), ('Ksiądz', 'ks. lic.'), ('', '')], default='', max_length=9)),
            ],
        ),
    ]
