# Generated by Django 3.0.5 on 2020-04-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.CharField(blank=True, choices=[('mgr', 'Magister'), ('mgr inż.', 'Magister Inz'), ('lic.', 'Licencjat'), ('inż.', 'Inzynier'), ('ks.', 'Ksiadz'), ('ks. lic.', 'Ksiadz Lic'), ('ks. mgr', 'Ksiadz Mgr'), ('', 'Brak')], default='', max_length=9),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DurationField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Member')),
            ],
        ),
    ]
