# Generated by Django 3.0.5 on 2020-04-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200420_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadence',
            name='member',
        ),
        migrations.RemoveField(
            model_name='position',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='cadence',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Cadence'),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Position'),
        ),
        migrations.AlterField(
            model_name='cadence',
            name='end',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='cadence',
            name='start',
            field=models.IntegerField(default=2020),
        ),
    ]
