# Generated by Django 3.0.5 on 2020-04-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200421_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadence',
            name='start',
            field=models.IntegerField(default=2019),
        ),
        migrations.RemoveField(
            model_name='member',
            name='cadence',
        ),
        migrations.AddField(
            model_name='member',
            name='cadence',
            field=models.ManyToManyField(to='staff.Cadence'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ManyToManyField(to='staff.Position'),
        ),
    ]
