# Generated by Django 3.0.5 on 2020-04-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200421_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadence',
            options={'ordering': ['-end']},
        ),
    ]
